# Geometric VAE version
compute_metrics_every: 1
use_c: True
trainable_c: True
l2: True
eta_interp: 0
interpolate_z: False
start_jac_after: 0
detach_theta: False
fl_weight: 1
anneal_fl_weight: False
max_fl_weight: Null
n_epochs_anneal_fl: Null
fl_anneal_fraction: Null