wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1743340511.248085
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.10.16
      5: 0.16.1
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: training_losses.loss_d
      5: 1
      6:
      - 1
    - 1: training_losses.loss_e
      5: 1
      6:
      - 1
    - 1: training_losses.loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
