seml:
  executable: ../PerturbSeq_CMV/train.py
  name: default_run
  output_dir: /nfs/homedirs/pala/PerturbSeq_CMV/project_folder/experiments
  conda_environment: PerturbSeq_CMV
  project_root_dir: ../PerturbSeq_CMV

slurm:
  max_simultaneous_jobs: 1
  experiments_per_job: 1
  sbatch_options_template: GPU
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 90G          # memory
    cpus-per-task: 6  # num cores
    time: 2-00:00     # max time, D-HH:MM

########## HUPERPARAMETER TUNING ##########

fixed: 
    # General hparameters 
    training.training:
      task_name: train
      seed: 42

    # Datamodule hyperparameters 
    datamodule.datamodule:
      path: /nfs/homedirs/pala/PerturbSeq_CMV/project_folder/data/processed/unperturbed_time_course_host.h5ad
      train_val_test_split: [0.80, 0.1, 0.1]
      max_dim: null
      batch_size: 128
      num_workers: 6
      pin_memory: False
      label_name: experimental_time 
      multi_modal: False
      modality_selection_key: is_host
      use_pca: False

    # Augmentations
    augmentations.augmentations:
      cnf_estimator: null
      l1_reg: 0.
      l2_reg: 0.
      squared_l2_reg: 0.
      jacobian_frobenius_reg: 0.
      jacobian_diag_frobenius_reg: 0.
      jacobian_off_diag_frobenius_reg: 0.

    # Net
    net.net:
      hidden_dims: [64, 64, 64]
      batch_norm: False
      activation: selu

    # Model
    model.model:
      ot_sampler: exact
      sigma_min: 0.1
      leaveout_timepoint: -1
      avg_size: -1
      lr: 0.001
      weight_decay: 0.00001

    # Callbacks 
    model_checkpoint.model_checkpoint:
      filename: "epoch_{epoch:04d}"
      monitor: val/loss
      mode: min
      save_last: True
      auto_insert_metric_name: False

    early_stopping.early_stopping:
      monitor: val/loss
      patience: 100
      mode: min

    # Logger 
    logger.logger:
      offline: False
      id: null # pass correct id to resume experiment!
      anonymous: null # enable anonymous logging
      project: "PerturbSeq_CMV"
      log_model: False # upload lightning ckpts
      prefix: "" # a string to put at the beginning of metric keys
      group: ""
      tags: []
      job_type: ""

    # Trainer
    trainer.trainer:
      min_epochs: 1 
      max_epochs: 100
      accelerator: gpu
      devices: 1
      check_val_every_n_epoch: 1
      deterministic: False
