# @package _global_

# Default configurations
defaults:
  - _self_
  - hydra: geom_vae
  - datamodule: 1_sweep_geom_eb
  - checkpoint: geom_vae
  - early_stopping: geom_vae
  - logger: 1_sweep_geom_eb
  - model: geom_vae
  - net: null
  - train: 1_sweep_geom_eb
  - trainer: geom_vae
  - launcher: slurm_cluster
  - hparams_search: null
  - geometric_vae: null
