path: ../project_folder/data/pancreas/flat/pancreas.h5ad
x_layer: X_latents
time_key: experimental_time
use_pca: False
n_dimensions: Null
train_val_test_split: [0.80, 0.2]
batch_size: 256
num_workers: 2
model_library_size: True