perform_early_stopping: False
monitor: train/loss  # KL and reconstruction combination
patience: 200
mode: min
min_delta: 0. 
verbose: False 
strict: True 
check_finite: True 
stopping_threshold: null 
divergence_threshold: null 
check_on_train_epoch_end: null 